name: Build

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: docker run raz0red/devkitppc /opt/devkitpro/pacman/bin/pacman -Q
    - run: docker run -v $(pwd):/source raz0red/devkitppc /source/dist.sh /tmp/wiimednafen
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
