name: Build

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Docker
      run: |
        docker pull raz0red/devkitppc

    - name: Update package list
      run: docker run raz0red/devkitppc /opt/devkitpro/pacman/bin/pacman -Q

    - name: Convert dist.sh to Unix line endings
      run: dos2unix dist.sh

    - name: Verify dist.sh existence and permissions
      run: |
        if [ ! -f dist.sh ]; then
          echo "Error: dist.sh not found!"
          exit 1
        fi
        if [ ! -x dist.sh ]; then
          chmod +x dist.sh
        fi

    - name: Run dist.sh
      run: docker run -v $(pwd):/source raz0red/devkitppc /bin/bash -c "/source/dist.sh /tmp/wiimednafen"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist